name: mlff-preconditioner
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.7.16
  - pip:
    - matplotlib==3.5.3
    - pandas==1.3.5
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - torch==1.13.1
    - torchvision==0.14.1
    - tqdm==4.66.1